import { LegalPage, type LegalSection } from "../../components/LegalPage";

const sections: LegalSection[] = [
  {
    title: "1. Information We Collect",
    content:
      "When you use Sparkle, we may collect information needed to provide and improve the service. This may include information you provide directly, usage data such as browser and device details, and communication data from support messages or emails.",
  },
  {
    title: "2. How We Use Your Information",
    content:
      "We use collected information to fulfill orders, communicate about accounts and support requests, prevent fraud and abuse, improve the platform, and send service-related notifications. We do not sell personal information or build advertising profiles.",
  },
  {
    title: "3. Legal Bases for Processing",
    content:
      "Where applicable law requires a legal basis, Sparkle processes data because it is necessary to provide requested services, comply with legal obligations, pursue legitimate interests such as fraud prevention and site security, or act on consent where consent-based storage or optional preferences are enabled.",
  },
  {
    title: "4. Information Sharing and Disclosure",
    content:
      "Sparkle does not sell, rent, or trade personal information. Limited information may be shared with trusted providers such as payment processors and hosting providers when necessary to operate the service. Information may also be disclosed when required by law.",
  },
  {
    title: "5. Data Retention",
    content:
      "We retain personal data only for as long as necessary for the purposes for which it was collected or as required by applicable legal obligations. Upon account deletion, personal data will be removed or anonymized within a reasonable period unless retention is required by law.",
  },
  {
    title: "6. Data Security",
    content:
      "Sparkle uses reasonable technical and organizational measures to protect personal information from unauthorized access, disclosure, alteration, or destruction. No method of internet transmission or electronic storage is completely secure, so absolute security cannot be guaranteed.",
  },
  {
    title: "7. Cookies, Local Storage and Preference Technologies",
    content:
      "Sparkle uses a small amount of first-party storage for site operation and optional preferences. We do not use advertising cookies and we do not permit third-party trackers to build cross-site behavioral profiles from this portfolio.",
    listNote: "Storage categories used on the site may include:",
    list: [
      "Necessary storage for consent state, basic fraud-resistance, navigation continuity, and core site functionality.",
      "Optional preference storage for language selection and interface preferences such as visual interaction settings.",
      "Security-related request and hosting logs generated by infrastructure providers for abuse monitoring, rate limiting, and incident response.",
    ],
    listFooter:
      "You may decline optional preference storage and still access the core site. Browser-level cookie controls may also be used, though disabling all storage can limit some interface behavior.",
  },
  {
    title: "8. Your Rights",
    content:
      "Depending on your jurisdiction, you may have rights to access, correct, delete, restrict, object to processing, withdraw consent, or request portability of your personal data. We may ask you to verify your identity before processing a request in order to protect account and transaction security.",
    contact: "help@sw8tx.lol",
  },
  {
    title: "9. Children's Privacy",
    content:
      "The Sparkle platform is not intended for individuals under 13. We do not knowingly collect personal information from children under 13. If a parent or guardian believes a child has provided personal information, they should contact us so we can review and delete it where required.",
  },
  {
    title: "10. Third-Party Links and Services",
    content:
      "The platform may contain links to external services not operated by Sparkle. This Privacy Policy applies only to information collected by Sparkle. We encourage users to review third-party privacy policies before using external services.",
  },
  {
    title: "11. International Data Transfers",
    content:
      "If you access Sparkle from outside the country where our servers or providers operate, your data may be transferred across borders. We take steps to ensure information receives appropriate protection in line with this Privacy Policy and applicable law.",
  },
  {
    title: "12. Data Breach and Security Response",
    content:
      "Sparkle monitors hosting and platform security events and may work with infrastructure providers to investigate abuse, unauthorized access attempts, or service disruption. Where legally required, affected users and relevant authorities will be notified of qualifying data incidents within the timelines required by applicable law.",
  },
  {
    title: "13. Changes to This Policy",
    content:
      "Sparkle may update this Privacy Policy at any time. When changes are made, the updated date will be revised. Continued use of the service after updates are posted constitutes acceptance of the revised policy.",
  },
  {
    title: "14. Contact Us",
    content:
      "If you have questions, concerns, or requests regarding this Privacy Policy, storage preferences, or how we handle personal data, please use the contact method below. We aim to respond within 48 hours on business days.",
    contact: "help@sw8tx.lol",
  },
];

export default function Privacy() {
  return (
    <LegalPage
      tone="privacy"
      label="Privacy"
      title="Privacy Policy"
      updated="Last updated: June 2026"
      sections={sections}
    />
  );
}
